### ISSUE TITLE
Document Supported and Unsupported IFC Features

### ISSUE THREAD

**Issue by cdiggins** [tomvandig/web-ifc#109]
For us to start considering using this library in production code, we would need to know what the list of supported and unsupported IFC features and known issues is.

**Comment by cdiggins** [comment]
Hi @tomvandig sorry about the confusion, I was requesting this as a feature of the library/repo, unfortunately I can't actually volunteer at the current time. Right now, my team is using XBim to convert IFC to the VIM format as a service and it is working relatively well. 

That said, do you think there is some way the list of supported/unsupported IFC features could be automatically generated? 

By the way, I looked at the code, and it is very elegant. I was impressed at how much you are able to achieve with a very succinct and easy to understand system. Good job!

**Comment by tomvandig** [comment]
Hi, I could maybe auto-generate somehow which IFC types are referenced in the code, which would in turn give an indication that they are, at least to some extent, supported. However, by that metric the lib has supported certain types for many months even though they are not yet correctly implemented (example: sweptsolids).

What I can say is that we currently work from the 4.2 spec and so from a parsing-perspective we support 4.2 completely. But from a geometry perspective the picture is less clear. If you want to find out for your models you can just drag them into the viewer, and any unsupported items will be printed to the console, but this won't tell you about objects which are supported but appear incorrect. A real investigation of support would need either a catalog of files and a reference geometry generator, or a human being to judge the various IFC elements and configurations.

For the foreseeable future, I will have to spend my time on improving support, rather than measuring it, even though I am just as curious as you to know the outcome :)
