### ISSUE TITLE
BUG: IFC mappedItem

### ISSUE THREAD

**Issue by vegarringdal** [tomvandig/web-ifc#131]
hi @tomvandig 

Unable to render this in the demo (see image below, no 2)
Was hoping to try and look more into instancing, from what I understand I will need the mappedItem type to work.
If you have used IFC and instancing before and have any tips for me, then that would be appreciated :-)

Ref
https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/mapped-shape-with-multiple-items.htm

![image](https://user-images.githubusercontent.com/2901416/149970527-15766479-90e3-4588-9185-c8c4532ae741.png)

file:
https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/mapped-shape-with-multiple-items.ifc

Error
![image](https://user-images.githubusercontent.com/2901416/149970383-827c637d-4b01-42f9-bf87-e9333c349ef8.png)

**Comment by agviegas** [comment]
This issue is now a bounty. Whoever solves this will get $200. More information [here](https://bounties.ifcjs.io/).

**Comment by QuimMoya** [comment]
Apogea here, we expect to solve this bounty today

**Comment by QuimMoya** [comment]
Solved, there was a problem parsing the IFC

...
#33= IFCRECTANGLEPROFILEDEF(.AREA.,'1m x 1m rectangle',**$**,1000.,1000.);
...

This $ caused a lot of trouble because IFC.js does not find any location for the object. By creating a default location the problem gets solved.

Now the model is properly represented and scaled as a mappeditem

Scale 0.5
![image](https://user-images.githubusercontent.com/12625508/168813578-959a33f7-66fe-42fe-ac26-8e75f31ce106.png)

scale 0.25
![image](https://user-images.githubusercontent.com/12625508/168813757-b8529661-1eaa-4b39-822f-dfc5cf79bea5.png)

**Comment by QuimMoya** [comment]
There are still some differences with other viewers i will continue to work on it.

**Comment by QuimMoya** [comment]
Finally, it seems to work properly now

![image](https://user-images.githubusercontent.com/12625508/168900368-c95bca11-65b1-41c7-8384-765f05bdbb91.png)
Comaprison BimVision vs IFC.JS
