### ISSUE TITLE
Fails to load certain parts of an IFC

### ISSUE THREAD

**Issue by lewibs** [tomvandig/web-ifc#152]
Attached are the screenshots I took of the issue. When I loaded the ifc into the browser It failed to load the yellow components that are shown in the BIMViewer picture.
https://photos.app.goo.gl/5SvUep3zwMsAwmzY9

Here is the ifc that was loaded. I had the same issue with a few other files.
https://drive.google.com/file/d/1UFl0hz8nkoh_-oDxJ_xZxa6fc24mm3KB/view?usp=sharing

**Comment by QuimMoya** [comment]
The problem is in the IFC file, there are entities that are in lower case
...
#2236=**IfcColumn**('3xCJf4w5T5eOsxS6AsIGQG',#2205,'GENSEC 1 of FRMWORK /B01_LEVEL_01_COLUMNS',$,'BS-UC305x305x137',#2225,#2235,'=2013286654/30950',.USERDEFINED.);
#2205=**IfcOwnerHistory**(#2202,#2204,$,.NOCHANGE.,$,$,$,1637178735);
#2202=**IfcPersonAndOrganization**(#2200,#2201,$);
...

It should be UPPERCASE. The proof is in the STEP ISO 10303 specification

**Comment by agviegas** [comment]
Solved [here](https://github.com/tomvandig/web-ifc/pull/161). Will be available from 0.0.35.
