### ISSUE TITLE
What is the best way to report missing geometry?

### ISSUE THREAD

**Issue by harrycollin** [tomvandig/web-ifc#16]
I've been testing different models and have found a couple of geometry bugs. What's the best way to report them? Thanks :)

![image](https://user-images.githubusercontent.com/10602138/111139853-8b53e400-8579-11eb-9fa8-18b743c7d53e.png)

**Comment by tomvandig** [comment]
Hi Harry, 

Thanks for your interest in this lib!

For the specific model above: we're also testing it and we'll get around to each problem at some point :)

However, for your general question: please open individual tickets with the model and broken element GUIDs, this way I can most quickly get to solving the problems.

Also, please check the latest version of the lib always, that saves me some time if the problem is already solved 👍 

Cheers!

**Comment by harrycollin** [comment]
Thank you
