### ISSUE TITLE
CSG errors on IFC example model

### ISSUE THREAD

**Issue by haroldiedema** [tomvandig/web-ifc#17]
As per request from @agviegas, created a separate issue for this. The original model comes from an IFC wikipedia page and is used as an 'example' model. It seems that _a lot_ of vertices are generated which are not needed.

You can download the model here: https://iedema.me/haus.ifc

![image](https://user-images.githubusercontent.com/567518/111156021-8c930a00-8595-11eb-9a73-f3e9019356c2.png)

**Comment by tomvandig** [comment]
Hi, 

Thanks for posting this issue!

I was rolling a handmade CSG lib, but it's been a pain so I've decided to migrate to another CSG lib. Hopefully this one will last longer 👍 

The attached model now looks like this:
![image](https://user-images.githubusercontent.com/49716596/111212169-90dc1900-85cf-11eb-989e-5e9578607a57.png)

There's a small remaining issue with the windows, as each of the voids in this mesh are actually two extruded solids instead of one. Not sure if I should blame the CSG lib or the ifc model now...

**Comment by haroldiedema** [comment]
This looks pretty much the same as when I used this model using the CLI tool (ifc-convert) to convert the model to a COLLADA file. The z-fighting in the roof and beams were also there :smile: 

Looks good! :tada:
