### ISSUE TITLE
Cannot get a bounding box for a given expressID

### ISSUE THREAD

**Issue by ericpasquiet** [tomvandig/web-ifc#179]
Hello,

I am trying to write a command to reframe the camera of my viewer on a specific object (modelID + expressID).
To do this, I need to compute the bounding box of that object, but I have not been able to find a way.

I have tried using the subsets of web-ifc-three, by creating a subset containing this object, and then doing a "getSubset" to obtain a mesh of that particular object (and then compute a bounding box around it), but the mesh returned is the one of the whole model.

Is there a solution to my problem?

Kind regards,

**Comment by agviegas** [comment]
Hey @ericpasquiet! The boundingbox is computed using `Mesh.geometry.attributes.position`. The problem is that, in order to save memory, all buffers are shared across the original geometry and all the subsets. Subsets use the `geometry.index` attribute to define what geometry it has (they are Indexed BufferGeometries). You can compute the bounding box yourself doing the following:

1. Get the subset whose bounding box you'd like to get.
2. Use it's indices to find out it's vertices. You can find the indices in `mesh.geometry.index`.
3. Traverse all its vertices and find the min and the max vertex.

Something like this:

```js
const coordinates = [];
const alreadySaved = new Set();
const position = subset.geometry.attributes.position;
for(let index of geometry.index.array) {
  if(!alreadySaved.has(index)){
    coordinates.add(position.getX(index));
    coordinates.add(position.getY(index));
    coordinates.add(position.getZ(index));
    alreadySaved.add(index);
  }
}
const vertices = Float32Array.from(coordinates);
```

You can find more information about buffergeometries [here](https://threejs.org/manual/#en/custom-buffergeometry).

Hope that this helps. Cheers!
