### ISSUE TITLE
Feature Request - Server side rendering for IFC

### ISSUE THREAD

**Issue by freshcutdevelopment** [tomvandig/web-ifc#36]
Many of our customers operate in low bandwidth environments such as remote areas, as such the idea of server rendering parts of the IFC model and streaming them to the client has much appeal for us.

In an ideal architecture, we'd be able to split the rendering across multiple Azure functions to make this scalable. Where the files are loaded from should be configurable to allow loading from Azure blob storage / AWS buckets or similar.

**Comment by tomvandig** [comment]
This is out of scope for this repository: this repository is only concerned with parsing IFC files and producing a web-compatible library. However, what you want to do is an important use case and will probably be supported inside the IFC.js ecosystem at some point. When this will happen, I don't know, since we're all doing this in our spare time. If you would like to contribute this would be a nice project!

One example of this already exists, at https://github.com/xeokit/xeokit-ifc-to-xkt

The reason this is out of scope for this repo is that there is no canonical way to solve this problem, and I would like this library to remain flexible. Supporting functions, like outputting specific dataformats, may be included in web-ifc for performance reasons.

**Comment by freshcutdevelopment** [comment]
Thanks for the input @tomvandig much appreciated!
