### ISSUE TITLE
Geometry not rendered as expected with IfcBooleanClippingResult and IfcPolygonalBoundedHalfSpace

### ISSUE THREAD

**Issue by favreau84** [tomvandig/web-ifc#86]
# Problem

- web-ifc : 0.0.24
- Some geometries are not correctly rendered.
- File : [gourreau.ifc.zip](https://github.com/tomvandig/web-ifc/files/7225887/gourreau.ifc.zip)
- Incorrect geometry for the item with expressID : 2625
<img width="564" alt="
Capture d’écran 2021-09-24 à 15 17 40" src="https://user-images.githubusercontent.com/18169247/134681125-e6f981e9-e54e-4af4-bd09-d9ada00fc478.png">

# Investigation

- The elements that are not rendered correctly are specified with a IfcBooleanClippingResult & IfcPolygonalBoundedHalfSpace.
- Maybe the reason or not ... :-)

<img width="605" alt="Capture d’écran 2021-09-24 à 15 24 47" src="https://user-images.githubusercontent.com/18169247/134681936-b7e4cde9-1e68-49f7-b05d-1fc46bcf630a.png">

**Comment by tomvandig** [comment]
Took a while, but the halfspace problems are fixed in the latest version 0.0.30

There's still a problem in the model remaining, 1 triangle appears to disagree with my booleans.

![image](https://user-images.githubusercontent.com/49716596/144505614-a1649372-52c9-4eb8-8056-f627b88847a5.png)
![image](https://user-images.githubusercontent.com/49716596/144505631-1722156e-b943-4de9-aa74-70403d4a472f.png)

**Comment by favreau84** [comment]
@tomvandig , wahou !!! This is fantastic !!!!
This one triangle is the small necessary imperfection to bring beauty to the model :-)
Can't wait to use it in CAPLA :-) it seems that web-ifc-three (0.0.87) is still using 0.0.29
