### ISSUE TITLE
How to have a correct position for georeferenced model ?

### ISSUE THREAD

**Issue by loicroybon** [tomvandig/web-ifc#91]
Hello, I have an IFC model with high coordinates values (center : 1934745.48357, 4252640.72565, 258.547085938).
I want to merge this model with CesiumJS to display model on a 3D globe but I'm not able to have a correct implentation.

**case 1 : with COORDINATE_TO_ORIGIN: false**
Model display flickers (float limit)

**case 2 : with COORDINATE_TO_ORIGIN: true**
Model is very far from the real globe position

**case 3 : with COORDINATE_TO_ORIGIN: true + ifcModel.position.set(1934745.48357, 4252640.72565, 258.547085938); **
I can have the IFC model near from real position but : 
1. I have to set its values ​​arbitrarily
2. Orientation is still incorrect

![image](https://user-images.githubusercontent.com/73525724/137740023-a789c1c7-9a3f-46df-b18b-c9c6089e314b.png)

Explaination of the image : in withe, this is the projection of the correct position I need to obtain.

Question is : how is it planned to use georeferenced models with ifcjs?

**Comment by agviegas** [comment]
Hey @loicroybon I'm closing this for now. If you want to help us solve this, feel free to reopen it again and provide more information!

**Comment by autra** [comment]
Commenting here, because even though @loicroybon might have moved on, this still shows up when someone searches for orientation problem: what viewer are you using? 

From your screenshot and what I guess from your nationality, you might use itowns or giro3d. These viewer uses a z-up axis instead of the default y-up (because that's what we do in GIS). the solution is to apply a PI/2 rotation in the x axis of the model.
